kernel_modules:
  - v4l2loopback
  - sg

systemd_user_services:
  - password-store-sync.timer
  - zfs-backup.timer
  - udiskie.service
  - syncthing.service
  - mako.service
  - idocachesrv.service
  - elephant.service
  - walker.service
  - docker-hoster.service

base_packages:
  - iwd
  - openssh
  - ntp
  - grub
  - efibootmgr
  - zsh
  - sudo
  - fwupd
  - plymouth
  - mesa
  - mesa-utils

packages:
  # Personal repo
  - xdg-utils-handlr
  - neovim-symlinks
  - jetbrains-toolbox
  - slack-desktop
  - google-chrome
  - appimagelauncher
  - git-trim-bin
  - coolercontrold-bin
  - coolercontrol-bin
  - brscan5
  - brother-dcpt720dw
  - tofi
  - rpi-imager
  - zoom
  - coppwr-bin
  - k6
  - elephant
  - elephant-bluetooth
  - elephant-calc
  - elephant-clipboard
  - elephant-desktopapplications
  - elephant-files
  - elephant-menus
  - elephant-providerlist
  - elephant-runner
  - elephant-symbols
  - elephant-todo
  - elephant-unicode
  - elephant-websearch
  - walker
  - pinta
  # Personal repo end
  - neovim
  - git
  - fzf
  - starship
  - direnv
  - udiskie
  - libappindicator-gtk3
  - ghostty
  - wireplumber
  - pipewire
  - pipewire-pulse
  - pipewire-jack
  - pipewire-alsa
  - pipewire-libcamera
  - python
  - python-pip
  - python-pipx
  - python-setuptools
  - discord
  - jq
  - yq
  - thunar
  - tumbler
  - obs-studio
  - wiremix
  - jdk-openjdk
  - openjdk-src
  - gcr
  - bluez
  - bluez-utils
  - bluetui
  - ccid
  - pcsclite
  - mako
  - firefox
  - bc
  - htop
  - python-pynvim
  - sshpass
  - the_silver_searcher
  # Fonts
  - ttf-fira-code
  - ttf-font-awesome
  - ttf-liberation
  - ttf-cascadia-mono-nerd
  - ttf-jetbrains-mono-nerd
  - otf-ipafont
  - noto-fonts
  - noto-fonts-cjk
  - noto-fonts-emoji
  - noto-fonts-extra
  - terminus-font
  # Fonts end
  - zip
  - unzip
  - vlc
  - v4l2loopback-dkms
  - texlive
  - ncdu
  - pandoc
  - man-db
  - imagemagick
  - vulkan-tools
  - dos2unix
  - libva-mesa-driver
  - libva-utils
  - waybar
  - postgresql-libs
  - flatpak
  - docker
  - docker-compose
  - docker-buildx
  - xreader
  # Podman
  - podman
  - buildah
  - fuse-overlayfs
  - cni-plugins
  # Podman end
  - nmap
  - yubikey-manager
  - avahi
  - nss-mdns
  - cups
  - cups-browsed
  - cups-filters
  - cups-pdf
  - gutenprint
  - foomatic-db-gutenprint-ppds
  - sane
  - sane-airscan
  - simple-scan
  - usbutils
  - go
  - ripgrep
  - fd
  - kubectl
  - tarsnap
  - pgcli
  - xorg-xwayland
  - xorg-xinput
  - sway
  - cifs-utils
  - handbrake
  - terraform
  - slurp
  - qt5ct
  - qt6ct
  - qt6-wayland
  - qt5-wayland
  - kvantum
  - kvantum-qt5
  - wl-clipboard
  - tailscale
  - wtype
  - imv
  - vulkan-validation-layers
  - handlr-regex
  - stow
  - azote
  - nwg-displays
  - nwg-look
  - gnome-software
  - gnome-calculator
  - gnome-keyring
  - gnome-themes-extra
  - zoxide
  - yazi
  - redis
  - filezilla
  - xournalpp
  - uwsm
  - weechat
  - impala
  - cdrdao
  - gvfs-nfs
  - gvfs-smb
  - yaru-icon-theme
  - papirus-icon-theme
  - syncthing
