host_kernel_modules: []

host_systemd_user_services: []

host_packages:
  - "@Sway Desktop"
  - NetworkManager-tui
  - blueman
  - pinentry-gnome3
  - gcr3
  - pavucontrol
  # Satty
  - libepoxy-devel
  - libadwaita-devel
  - rustup
  # Satty end
  - fuse
  - fzf
  - pass
  # Tofi
  - meson
  - scdoc
  - wayland-protocols-devel
  - wtype
  - freetype-devel
  - cairo-devel
  - pango-devel
  - wayland-devel
  - libxkbcommon-devel
  - harfbuzz
  # Tofi end
  - udiskie
  - libappindicator-gtk3
  - java-21-openjdk
  - libreoffice
  - inkscape
  - gimp
  - vlc
  - mpv
  - ImageMagick
  - papirus-icon-theme
  #- "https://github.com/ferdium/ferdium-app/releases/download/v7.0.0/Ferdium-linux-7.0.0-aarch64.rpm"
  - ripgrep
  - the_silver_searcher
  - pandoc
  - golang
  - azote
  - fira-code-fonts
  - Thunar

host_aur_packages: []

video_driver: apple
