host_kernel_modules:
  - it87

host_systemd_user_services:
  - tarsnap.timer

host_packages:
  - amd-ucode
  - xf86-video-amdgpu
  - vulkan-radeon
  - steam
  - liquidctl
  # Personal repo
  - it87-dkms-git
  - obs-vkcapture
  - cemu-bin
  - makemkv
  - protonup-qt
  # Personal repo end

host_flatpak_packages:
  - com.steamgriddb.SGDBoop
  - com.usebottles.bottles
  - io.github.lime3ds.Lime3DS
  - io.github.shiiion.primehack

video_driver: amdgpu
