#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

~/.local/bin/bar.sh

bspc monitor DP1-3 -d 1 2 3 4 5
bspc monitor eDP1 -d 6 7 8 9 10

bspc config border_width 1
bspc config window_gap 5

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
