#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

~/.local/bin/bar.sh

lxsession &
xss-lock /usr/bin/slock &
xautolock -time 10 -locker '/usr/bin/loginctl lock-session $XDG_SESSION_ID' -detectsleep &
picom &

setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl
autorandr -c
feh --bg-fill ~/Pictures/wallpaper.jpg ~/Pictures/wp4181214.jpg

bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7
bspc monitor DisplayPort-0 -d 8
bspc wm --reorder-monitors HDMI-A-0 DisplayPort-0

bspc config border_width 1
bspc config window_gap 5

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
